---
- hosts: 
  become: yes
  #remote_user:
  tasks:
    - name: Adicionando repositorio Zabbix
      shell: rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
      ignore_errors: yes

    - name: Limpando Metadaos
      shell: yum clean all

    - name: Instalando o zabbix-agent
      yum:
        name: zabbix-agent
        state: present
            
    - name: Copia arquivo de zabbix-agent.conf e verifica se ja tem o arquivo localmente
      template:
        src: /tmp/teste.j2 #necessário alterar caminho, informando onde está o arquivo de config na maquina local
        dest: /etc/zabbix/zabbix_agentd.config
        force: no

    - name: Restartando serviço do zabbix-agent
      service:
        name: zabbix-agent 
        state: started

    - name: Habilitando o zabbix junto a inicialização
      service:
        name: zabbix-agent
        enabled: yes
...
